apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: suilens-2306275935
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - databases.yaml
  - rabbitmq.yaml
  - apps.yaml
  - ingress.yaml
