apiVersion: batch/v1
kind: Job
metadata:
  name: suilens-migrate
  namespace: suilens-2306275935
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate-catalog
          image: alphasuthamedia/suilens-catalog-service:latest
          command: ["bunx", "drizzle-kit", "push"]
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: suilens-config
                  key: CATALOG_DATABASE_URL

        - name: migrate-order
          image: alphasuthamedia/suilens-order-service:latest
          command: ["bunx", "drizzle-kit", "push"]
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: suilens-config
                  key: ORDER_DATABASE_URL

        - name: migrate-notification
          image: alphasuthamedia/suilens-notification-service:latest
          command: ["bunx", "drizzle-kit", "push"]
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: suilens-config
                  key: NOTIFICATION_DATABASE_URL
