apiVersion: v1
kind: ConfigMap
metadata:
  name: suilens-config
  namespace: suilens-2306275935
data:
  CATALOG_DATABASE_URL: postgres://catalog:catalog@catalog-db:5432/catalog
  ORDER_DATABASE_URL: postgres://orders:orders@order-db:5432/orders
  NOTIFICATION_DATABASE_URL: postgres://notifications:notifications@notification-db:5432/notifications
  CATALOG_SERVICE_URL: http://catalog-service:3001
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  VITE_CATALOG_API: http://localhost:3001
  VITE_ORDER_API: http://localhost:3002
  VITE_NOTIFICATION_WS: ws://localhost:3003/ws/notifications
