kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: suilens-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000  # frontend
        hostPort: 5173
        protocol: TCP
      - containerPort: 30001  # catalog-service
        hostPort: 3001
        protocol: TCP
      - containerPort: 30002  # order-service
        hostPort: 3002
        protocol: TCP
      - containerPort: 30003  # notification-service
        hostPort: 3003
        protocol: TCP
  - role: worker
  - role: worker
