apiVersion: v1
kind: Secret
metadata:
  name: suilens-secrets
  namespace: suilens-2306275084
type: Opaque
stringData:
  POSTGRES_CATALOG_USER: catalog
  POSTGRES_CATALOG_PASSWORD: catalog
  POSTGRES_CATALOG_DB: catalog
  POSTGRES_ORDER_USER: orders
  POSTGRES_ORDER_PASSWORD: orders
  POSTGRES_ORDER_DB: orders
  POSTGRES_NOTIFICATION_USER: notifications
  POSTGRES_NOTIFICATION_PASSWORD: notifications
  POSTGRES_NOTIFICATION_DB: notifications
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
